from setuptools import setup, find_packages

setup(
    name='sres',
    version='0.1',
    long_description=__doc__,
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'Flask',
        'Flask_WTF',
        'APScheduler',
        'Flask_Mail',
        'chardet',
        'natsort',
        'pymongo',
        'cexprtk',
        'pandas',
        'scipy',
        'requests',
        'Flask_Session',
        'bleach',
        'pycryptodome',
        'python_Levenshtein',
        'beautifulsoup4',
        'python_dateutil',
        'qrcode',
        'Pillow',
        'python_barcode',
        'xlrd'
    ]
)