import unittest
import time
import datetime
import os
import re
import json

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.remote.command import Command

from sres.tests import config
from sres.tests import utils as test_utils

options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('window-size=1600,900')

class TestBase(unittest.TestCase):
    
    def setUp(self):
        self.driver = webdriver.Chrome(config.CHROMEDRIVER_PATH, chrome_options=options)
        
        # Create test users
        self.list_admin = test_utils.create_test_user(['list', 'filter'])
        assert self.list_admin['username'] and self.list_admin['password']
        self.list_student = test_utils.create_test_user(['student'])
        assert self.list_student['username'] and self.list_student['password']
        
        self.driver.get(config.URL_BASE)
        self.driver.find_element_by_id('loginUsername').send_keys(self.list_admin['username'])
        self.driver.find_element_by_id('loginPassword').send_keys(self.list_admin['password'])
        self.driver.find_element_by_id('login_button').click()
        assert "SRES" in self.driver.title
        assert self.list_admin['username'] in self.driver.find_element_by_id('logged_in_username').text
        time.sleep(2)
        
    def tearDown(self):
        self.driver.quit()
    
class TestTextSubstitutions(TestBase):
    
    def _sendkeys_for_column_edit(self, column_name, column_type, column_description=None):
        
        self.driver.find_element_by_id('columnname').send_keys(column_name)
        self.driver.find_element_by_id('columndescription').send_keys(
            column_description if column_description else "Generated by testing suite"
        )
        for date_button in self.driver.find_elements_by_class_name('sres-date-shortcut-today'):
            if date_button.is_displayed():
                date_button.click()
        self.driver.find_element_by_id('dataType-' + column_type).click()
    
    def _sendkeys_for_multientry_selectable_options(self, n, options):
        
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_editor_select_' + str(n))
        time.sleep(0.5)
        
        assert self.driver.find_element_by_id('modal_select_from_list_editor').is_displayed()
        
        for option in options:
            self.driver.find_element_by_id('select_from_list_add_option').click()
            
        display_inputs = self.driver.find_elements_by_css_selector('.sres-select-from-list-row:not(.d-none) .sres-select-from-list-row-display')
        for i, el in enumerate(display_inputs):
            if 'display' in options[i]:
                test_utils.move_to_element(self.driver, el)
                el.send_keys(options[i]['display'])
        
        value_inputs = self.driver.find_elements_by_css_selector('.sres-select-from-list-row:not(.d-none) .sres-select-from-list-row-value')
        for i, el in enumerate(value_inputs):
            if 'value' in options[i]:
                test_utils.move_to_element(self.driver, el)
                el.send_keys(options[i]['value'])
            
        more_toggle_inputs = self.driver.find_elements_by_css_selector('.sres-select-from-list-row:not(.d-none) .sres-select-from-list-row-more-options-toggle')
        for i, el in enumerate(more_toggle_inputs):
            test_utils.move_to_element(self.driver, el)
            el.click()
        description_inputs = self.driver.find_elements_by_css_selector('.sres-select-from-list-row:not(.d-none) .sres-select-from-list-row-description')
        for i, el in enumerate(description_inputs):
            if options[i]['description']:
                el.send_keys(options[i]['description'])
        
        test_utils.move_to_click_element_by_id(self.driver, 'modal_select_from_list_editor_confirm')
        time.sleep(0.2)
        
        assert not self.driver.find_element_by_id('modal_select_from_list_editor').is_displayed()
    
    def test_text_substitutions(self):
        
        from sres.tests import test_list_crud
        _id, new_list_uuid = test_list_crud.TestListCRUD._create_list(self)
        assert new_list_uuid
        print('Created new list ' + new_list_uuid)
        
        print('Adding student to list')
        test_utils.add_student_to_list(self.driver, new_list_uuid, self.list_student['user'])
        
        ###########################
        # Create timestamp (submission) column
        ###########################
        new_timestamp_column_name = "Timestamp test 1"
        print('Creating timestamp column: ' + new_timestamp_column_name)
        self.driver.get(config.URL_BASE + '/tables/' + new_list_uuid + '/columns/new/standard')
        self._sendkeys_for_column_edit(column_name=new_timestamp_column_name, column_type="submission")
        test_utils.move_to_click_element_by_id(self.driver, 'submitButton')
        assert "Column configuration successfully updated" in self.driver.page_source
        new_timestamp_column_uuid = re.findall('COL_[A-F0-9a-f_]+', self.driver.current_url)[0]
        assert new_timestamp_column_uuid
        print('Created new timestamp column ' + new_timestamp_column_uuid)
        
        ###########################
        # Create simple entry (mark) column
        ###########################
        new_simple_column_name = "Simple entry test 1"
        print('Creating simple column: ' + new_simple_column_name)
        self.driver.get(config.URL_BASE + '/tables/' + new_list_uuid + '/columns/new/standard')
        self._sendkeys_for_column_edit(column_name=new_simple_column_name, column_type="mark")
        test_utils.select_by_value_in_element_by_css_selector(self.driver, '#allowFreeInput > div > select', 'true')
        test_utils.move_to_click_element_by_id(self.driver, 'submitButton')
        assert "Column configuration successfully updated" in self.driver.page_source
        new_simple_column_uuid = re.findall('COL_[A-F0-9a-f_]+', self.driver.current_url)[0]
        assert new_simple_column_uuid
        print('Created new simple column ' + new_simple_column_uuid)
        
        ###########################
        # Create multi-entry column
        ###########################
        new_multientry_column_name = "Multientry test 1"
        print('Creating multientry column: ' + new_multientry_column_name)
        self.driver.get(config.URL_BASE + '/tables/' + new_list_uuid + '/columns/new/standard')
        self._sendkeys_for_column_edit(column_name=new_multientry_column_name, column_type="multiEntry")
        
        n = 1
        
        # subfield 1 - a simple text entry
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Simple text 1')
        n += 1
        
        # subfield 2 - a multiline text
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Multiline text 1')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'regex-long')
        n += 1
        
        # subfield 3 - a set of buttons
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Buttons 1')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'select')
        self._sendkeys_for_multientry_selectable_options(
            n,
            [
                {
                    'display': 'Poor',
                    'value': '1',
                    'description': ''
                },
                {
                    'display': 'OK',
                    'value': '3',
                    'description': ''
                },
                {
                    'display': 'Great',
                    'value': '5',
                    'description': ''
                }
            ]
        )
        n += 1
        
        # subfield 4 - a second set of buttons, multiple select
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Buttons 2 multi')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'select')
        time.sleep(0.5)
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_select_mode_' + str(n), 'multiple')
        self._sendkeys_for_multientry_selectable_options(
            n,
            [
                {
                    'display': 'Verbal',
                    'value': 'verbal',
                    'description': ''
                },
                {
                    'display': 'Written',
                    'value': 'written',
                    'description': ''
                },
                {
                    'display': 'Telekinetic',
                    'value': 'tele',
                    'description': ''
                }
            ]
        )
        n += 1
        
        # subfield 5 - a dropdown
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Dropdown 1')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'dropdown')
        self._sendkeys_for_multientry_selectable_options(
            n,
            [
                {
                    'display': 'Fail',
                    'value': 'FA',
                    'description': ''
                },
                {
                    'display': 'Pass',
                    'value': 'PS',
                    'description': ''
                },
                {
                    'display': 'Distinction',
                    'value': 'DI',
                    'description': ''
                }
            ]
        )
        n += 1
        
        # subfield 6 - a multiple-select dropdown
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Dropdown 2 multi')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'dropdown')
        time.sleep(0.5)
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_select_mode_' + str(n), 'multiple')
        self._sendkeys_for_multientry_selectable_options(
            n,
            [
                {
                    'display': 'Flipping',
                    'value': 'flip',
                    'description': 'Flipping worked well.'
                },
                {
                    'display': 'Flapping',
                    'value': 'flap',
                    'description': 'Flapping performed exceptionally.'
                },
                {
                    'display': 'Flopping',
                    'value': 'flop',
                    'description': 'Flopping was well done.'
                }
            ]
        )
        n += 1
        
        # subfield 7 - a slider of type textual
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Slider 1')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'slider')
        time.sleep(0.5)
        test_utils.select_by_value_in_element_by_id(self.driver, 'multi_entry_slider_mode_' + str(n), 'textual')
        self._sendkeys_for_multientry_selectable_options(
            n,
            [
                {
                    'display': 'Fail',
                    'value': 'FA',
                    'description': ''
                },
                {
                    'display': 'Pass',
                    'value': 'PS',
                    'description': ''
                },
                {
                    'display': 'Distinction',
                    'value': 'DI',
                    'description': ''
                }
            ]
        )
        n += 1
        
        # subfield 8 - a slider of type free numeric
        test_utils.move_to_click_element_by_id(self.driver, 'multi_entry_add_row')
        test_utils.move_to_send_keys_element_by_id(self.driver, 'multi_entry_label_' + str(n), 'Slider 2')
        test_utils.select_by_value_in_element_by_name(self.driver, 'multi_entry_type_' + str(n), 'slider')
        time.sleep(0.5)
        test_utils.select_by_value_in_element_by_id(self.driver, 'multi_entry_slider_mode_' + str(n), 'numeric-free')
        self._sendkeys_for_multientry_selectable_options(
            n,
            [
                {
                    'display': '0',
                    'value': '0',
                    'description': ''
                },
                {
                    'display': 'Developing',
                    'value': '5',
                    'description': ''
                },
                {
                    'display': 'Developed',
                    'value': '10',
                    'description': ''
                },
                {
                    'display': 'Awesome',
                    'value': '20',
                    'description': ''
                }
            ]
        )
        n += 1
        
        # set roll view editor mode to popout
        test_utils.move_to_click_element_by_id(self.driver, 'btn_show_advanced_settings')
        test_utils.select_by_value_in_element_by_id(self.driver, 'custom_options_rollview_popout_editor', 'popout')        
        
        # save the column
        test_utils.move_to_click_element_by_id(self.driver, 'submitButton')
        assert "Column configuration successfully updated" in self.driver.page_source
        new_multientry_column_uuid = re.findall('COL_[A-F0-9a-f_]+', self.driver.current_url)[0]
        assert new_multientry_column_uuid
        print('Created new multientry column ' + new_multientry_column_uuid)
        
        # View list and check columns are there
        self.driver.get(config.URL_BASE + '/tables/' + new_list_uuid)
        time.sleep(5) # wait for page to load
        column_titles = [ c.text for c in self.driver.find_elements_by_css_selector('.sres-column-title > .sres-column-title-text') ]
        assert new_timestamp_column_name in column_titles
        assert new_simple_column_name in column_titles
        assert new_multientry_column_name in column_titles
          
        ####################
        # Test each column
        ####################
        
        sid1 = self.list_student['sid'] #'999888790'
        #sid1 = self.list_student['username'] # unsure which one works
        name1 = f"{self.list_student['given_names']} {self.list_student['surname']}" #'Warren Adamski'
        _test_string0 = test_utils.generate_random_string()
        _test_string1 = test_utils.generate_random_string()
        _test_string2 = test_utils.generate_random_string()
        
        # test timestamp column single mode
        print('Testing timestamp column data entry single: ' + new_timestamp_column_name)
        self.driver.get(f'{config.URL_BASE}/entry/table/{new_list_uuid}/columns/{new_timestamp_column_uuid}/single?identifier={sid1}')
        test_utils.save_screenshot(self.driver)
        assert name1 in self.driver.page_source
        time.sleep(1)
        assert self.driver.find_element_by_class_name('sres-addvalue-timestamp-checkbox').is_selected()
        timestamp_column_data = test_utils.read_db_data_value(new_list_uuid, new_timestamp_column_uuid, sid1)
        assert timestamp_column_data
        
        # test simple entry column single mode
        print('Testing simple column data entry single: ' + new_simple_column_name)
        self.driver.get(f'{config.URL_BASE}/entry/table/{new_list_uuid}/columns/{new_simple_column_uuid}/single?identifier={sid1}')
        assert name1 in self.driver.page_source
        time.sleep(1)
        self.driver.find_element_by_class_name('sres-addvalue-sase-text').send_keys(_test_string0)
        self.driver.find_element_by_class_name('sres-addvalue-sase-text').send_keys(Keys.ENTER)
        WebDriverWait(self.driver, 10).until(lambda x: x.find_element_by_css_selector('.fa-circle-notch.spinning.sres-addvalue-btn-save-status').is_displayed())
        WebDriverWait(self.driver, 5).until(lambda x: f"Successfully saved to server for {sid1}" in x.page_source)
        assert _test_string0 == test_utils.read_db_data_value(new_list_uuid, new_simple_column_uuid, sid1)
        
        # test multientry column single mode
        print('Testing multientry column data entry single: ' + new_multientry_column_name)
        self.driver.get(f'{config.URL_BASE}/entry/table/{new_list_uuid}/columns/{new_multientry_column_uuid}/single')
        assert new_multientry_column_name in self.driver.page_source
        self.driver.find_element_by_id('search_student_term').send_keys(sid1)
        WebDriverWait(self.driver, 10).until(lambda x: x.find_element_by_class_name('aa-with-search-results').is_displayed())
        self.driver.find_element_by_id('search_student_term').send_keys(Keys.ENTER)
        assert name1 in self.driver.page_source
        time.sleep(1)
        # interact with first subfield, singleline text
        _elem = self.driver.switch_to.active_element
        ActionChains(self.driver).move_to_element(_elem).send_keys(_test_string1).send_keys(Keys.TAB).perform()
        # interact with mutliline text
        self.driver.find_element_by_id(f'{new_multientry_column_uuid}_1_{sid1}').send_keys(_test_string2)
        # interact with single button
        self.driver.find_element_by_css_selector(f"button.sres-addvalue-multientry-button[data-sres-columnuuid='{new_multientry_column_uuid}'][data-sres-value='3']").click()
        # interact with multi button
        _elem = self.driver.find_element_by_css_selector(f"button.sres-addvalue-multientry-button[data-sres-value='written'][data-sres-columnuuid='{new_multientry_column_uuid}']")
        test_utils.move_to_click_element(self.driver, _elem)
        _elem = self.driver.find_element_by_css_selector(f"button.sres-addvalue-multientry-button[data-sres-value='tele'][data-sres-columnuuid='{new_multientry_column_uuid}']")
        test_utils.move_to_click_element(self.driver, _elem)
        # interact with single dropdown
        _elem = self.driver.find_element_by_css_selector(f"button[data-id={new_multientry_column_uuid}_4_{sid1}")
        ActionChains(self.driver).move_to_element(_elem).click(_elem).pause(0.2).send_keys(Keys.DOWN).pause(0.2).send_keys(Keys.DOWN).pause(0.2).send_keys(Keys.ENTER).perform()
        # use the more fields to interact with multi dropdown
        _elem = self.driver.find_element_by_css_selector(f"button[data-target='#{new_multientry_column_uuid}_5_{sid1}_more']")
        test_utils.move_to_click_element(self.driver, _elem)
        _elem = self.driver.find_element_by_css_selector("button[data-sres-multientry-item-value='flip']")
        test_utils.move_to_click_element(self.driver, _elem)
        _elem = self.driver.find_element_by_css_selector("button[data-sres-multientry-item-value='flop']")
        test_utils.move_to_click_element(self.driver, _elem)
        # interact with slider 1 and 2
        ActionChains(self.driver).send_keys(Keys.TAB).pause(0.2).send_keys(Keys.RIGHT).pause(0.2).send_keys(Keys.RIGHT).pause(1.0).send_keys(Keys.TAB).pause(0.2).send_keys(Keys.RIGHT).pause(0.2).send_keys(Keys.RIGHT).pause(0.2).send_keys(Keys.RIGHT).pause(0.2).send_keys(Keys.RIGHT).pause(0.2).send_keys(Keys.RIGHT).pause(1.0).perform()
        # save
        self.driver.execute_script("$('button.sres-addvalue-btn-save.sres-addvalue-save').click();")
        WebDriverWait(self.driver, 10).until(lambda x: x.find_element_by_css_selector('.fa-circle-notch.spinning.sres-addvalue-btn-save-status').is_displayed())
        WebDriverWait(self.driver, 5).until(lambda x: f"Successfully saved to server for {sid1}" in x.page_source)
        assert f"Successfully saved to server for {sid1}" in self.driver.page_source
        # check the saved data
        _saved_data = test_utils.read_db_data_value(new_list_uuid, new_multientry_column_uuid, sid1)
        _saved_data = json.loads(_saved_data)
        assert _saved_data[0] == _test_string1
        assert _saved_data[1] == _test_string2
        assert _saved_data[2] == '3'
        assert _saved_data[3] == ['written', 'tele']
        assert _saved_data[4] == 'PS'
        assert _saved_data[5] == ['flip', 'flop']
        assert _saved_data[6] == 'DI'
        assert _saved_data[7] == '5'
        
        #################
        # MAKE A FILTER #
        #################
        
        # TODO
        
        #################
        # MAKE A PORTAL #
        #################
        
        # new_timestamp_column_uuid, timestamp_column_data
        # new_simple_column_uuid, _test_string0
        # new_multientry_column_uuid, _test_string1, _test_string2
        
        _test_string3 = test_utils.generate_random_string()
        _test_string4 = test_utils.generate_random_string(40)
        _test_string5 = test_utils.generate_random_string(40)
        delim1 = test_utils.generate_random_string(5)
        
        print("Testing substitutions via a portal...")
        
        # build portal # TODO eventually refactor this into a portal test when built
        self.driver.get(f'{config.URL_BASE}/portals/new?source_table_uuid={new_list_uuid}')
        test_utils.save_screenshot(self.driver)
        assert "Create new portal" in self.driver.page_source
        time.sleep(5)
        test_utils.move_to_send_keys_element_by_id(self.driver, 'portal_name', f"Portal for testing {_id}")
        #self.driver.find_element_by_id('available_from').send_keys(datetime.datetime.now().strftime('%d/%m/%Y'))
        self.driver.find_element_by_id('available_from').send_keys('01012020')
        #self.driver.find_element_by_id('available_to').send_keys(datetime.datetime.now().strftime('%d/%m/%Y'))
        self.driver.find_element_by_id('available_to').send_keys('01012030')
        # make lots of panels
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.select_by_value_in_element_by_id(
            driver=self.driver,
            id='panel_showwhen-panel-x8',
            value='conditions'
        )
        test_utils.move_to_click_element_by_id(self.driver, 'add_panel')
        test_utils.select_by_value_in_element_by_id(
            driver=self.driver,
            id='panel_showwhen-panel-x9',
            value='conditions'
        )
        time.sleep(1)
        self.driver.execute_script(f"""
            $('#panel_content-panel-x1').html('{delim1} ${new_timestamp_column_uuid}$ {delim1}');
            $('#panel_content-panel-x2').html('{delim1} ${new_simple_column_uuid}$ {delim1}');
            $('#panel_content-panel-x3').html('{_test_string3}');
            $('#panel_content-panel-x4').html('${new_multientry_column_uuid}$');
            $('#panel_content-panel-x5').html(
                '{delim1} ${new_multientry_column_uuid}.0$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.1$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.2$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.3$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.4$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.5$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.6$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.7$ {delim1} '
            );
            $('#panel_content-panel-x6').html(
                '{delim1} ${new_multientry_column_uuid}.2.display$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.5.description$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.6.display$ {delim1} ' +
                '{delim1} ${new_multientry_column_uuid}.7.display$ {delim1} '
            );
            $('#panel_content-panel-x7').html(
                '${{join_bullets}} ${new_multientry_column_uuid}.5.description$ {{join_bullets}}$'
            );
        """)
        test_utils.save_screenshot(self.driver, 'x8')
        self.driver.execute_script(f"""
            // Set up panel 8 conditions
            $("#panel_conditions-panel-x8").queryBuilder(
                'setRules',
                {{
                    condition: 'AND',
                    not: false,
                    rules: [
                        {{
                            field: '{new_multientry_column_uuid}.2',
                            id: '{new_multientry_column_uuid}.2',
                            input: 'text',
                            operator: 'greater',
                            type: 'string',
                            value: '3'
                        }}
                    ],
                    valid: true
                }}
            );
            $('#panel_content-panel-x8').html(
                '{_test_string4}'
            );
        """)
        test_utils.save_screenshot(self.driver, 'x9')
        self.driver.execute_script(f"""
            // Set up panel 9 conditions
            $("#panel_conditions-panel-x9").queryBuilder(
                'setRules',
                {{
                    condition: 'AND',
                    not: false,
                    rules: [
                        {{
                            field: '{new_multientry_column_uuid}.4',
                            id: '{new_multientry_column_uuid}.4',
                            input: 'text',
                            operator: 'equal',
                            type: 'string',
                            value: 'PS'
                        }},
                        {{
                            field: '{new_simple_column_uuid}',
                            id: '{new_simple_column_uuid}',
                            input: 'text',
                            operator: 'equal',
                            type: 'string',
                            value: '{_test_string0}'
                        }}
                    ],
                    valid: true
                }}
            );
            $('#panel_content-panel-x9').html(
                '{_test_string5}'
            );
        """)
        test_utils.save_screenshot(self.driver, 'portal_settings')
        test_utils.move_to_click_element_by_id(self.driver, 'btn_save')
        assert "Portal configuration successfully updated" in self.driver.page_source
        portal_uuid = re.findall('(?<=portals/)[A-F0-9a-f_]+', self.driver.current_url)[0]
        print(f"Created portal {portal_uuid}")
        
        # test portal as student
        driver1 = webdriver.Chrome(config.CHROMEDRIVER_PATH, chrome_options=options)
        driver1.get(f'{config.URL_BASE}/portals/{portal_uuid}/view')
        driver1.find_element_by_id('loginUsername').send_keys(self.list_student['username'])
        driver1.find_element_by_id('loginPassword').send_keys(self.list_student['password'])
        driver1.find_element_by_id('login_button').click()
        time.sleep(1)
        test_utils.save_screenshot(driver1, 'portal_as_student')
        print(f"Testing portal {portal_uuid} as student with username {self.list_student['username']} password {self.list_student['password']}")
        
        ## check
        
        # new_timestamp_column_uuid, timestamp_column_data
        # new_simple_column_uuid, _test_string0
        # new_multientry_column_uuid, _test_string1, _test_string2
        
        assert _test_string3 in driver1.page_source
        
        print('Checking new_timestamp_column_uuid')
        assert f"{delim1} {timestamp_column_data} {delim1}" in driver1.page_source
        
        print('Checking new_simple_column_uuid')
        assert f"{delim1} {_test_string0} {delim1}" in driver1.page_source
        
        print('Checking new_multientry_column_uuid')
        assert f"{delim1} {_test_string1} {delim1}" in driver1.page_source
        assert f"{delim1} {_test_string2} {delim1}" in driver1.page_source
        assert f"{delim1} 3 {delim1}" in driver1.page_source
        assert f"{delim1} [\"written\", \"tele\"] {delim1}" in driver1.page_source
        assert f"{delim1} PS {delim1}" in driver1.page_source
        assert f"{delim1} [\"flip\", \"flop\"] {delim1}" in driver1.page_source
        assert f"{delim1} DI {delim1}" in driver1.page_source
        assert f"{delim1} 5 {delim1}" in driver1.page_source
        
        print('Checking magic formatters for new_multientry_column_uuid')
        assert f"{delim1} OK {delim1}" in driver1.page_source
        assert f"{delim1} Flipping worked well. Flopping was well done. {delim1}" in driver1.page_source
        assert f"{delim1} Distinction {delim1}" in driver1.page_source
        assert f"{delim1} Developing {delim1}" in driver1.page_source
        
        print('Checking multicolumn magic formatters for new_multientry_column_uuid')
        assert "<li>Flipping worked well.</li>" in driver1.page_source
        assert "<li>Flopping was well done.</li>" in driver1.page_source
        
        print('Checking conditional panels')
        assert _test_string4 not in driver1.page_source
        assert _test_string5 in driver1.page_source
        
        print('Portal testing complete.')
        
        
        
        
        
        
        
        
        
        
        
        # Delete list
        #test_list_crud.TestListCRUD._delete_list(self, _id)

if __name__ == '__main__':
    unittest.main()

